version: 0.2

phases:
  runtime-versions:
    nodejs: Latest
  install:
    commands:
      - echo "Installing dependencies"
      - npm install  
build:
    commands:
      - echo "Build phase started"
      - systemctl start nodejs
   

artifacts:
  files:
    - "**/*"
