version: 0.2

phases:
  install:
  commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Build phase started"
      - npm run start

artifacts:
  files:
    - "**/*"
