version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies"
      - yum install nodejs -y
       build:
    commands:
      - echo "Build phase started"
      - systemctl start nodejs
   

artifacts:
  files:
    - "**/*"
