version: 0.2

phases:
  install:
    commands:
      - nvm install node
      - node -v
    commands:
      - echo "Installing dependencies"
      - npm install  
build:
    commands:
      - echo "Build phase started"
      - systemctl start nodejs
   

artifacts:
  files:
    - "**/*"
